### ISSUE TITLE
corporation.getWarehouse: divisionName expected to be a string

### ISSUE THREAD

**Issue by prostriker87** [kamukrass/Bitburner#17]
TYPE ERROR
corp.js@home (PID - 139997)

corporation.getWarehouse: divisionName expected to be a string. Is undefined.

Stack:
corp.js:L90@upgradeWarehouses
corp.js:L20@main

**L18 solved: for (const division of corp.divisions.slice().reverse()) {**

**Comment by prostriker87** [comment]
RUNTIME ERROR
corp.js@home (PID - 176089)

Tobacco does not have a warehouse in 'Aevum'
stack:
Error: Tobacco does not have a warehouse in 'Aevum'
    at w (file:///F:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:9:311716)
    at file:///F:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:9:312729
    at Proxy.c (file:///F:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:9:231241)
    at upgradeWarehouses (home/corp.js:90:38)
    at main (home/corp.js:20:4)
    at R (file:///F:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:9:401635)

**Comment by prostriker87** [comment]
RUNTIME ERROR
corp.js@home (PID - 180385)

ns.corporation.unlockUpgrade is not a function
stack:
TypeError: ns.corporation.unlockUpgrade is not a function
    at initialCorpUpgrade (home/corp.js:356:17)
    at main (home/corp.js:13:9)
    at R (file:///F:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:9:401635)

**Comment by prostriker87** [comment]
RUNTIME ERROR
corp.js@home (PID - 182350)

ns.corporation.hasUnlockUpgrade is not a function
stack:
TypeError: ns.corporation.hasUnlockUpgrade is not a function
    at upgradeCorp (home/corp.js:117:22)
    at main (home/corp.js:20:4)
    at R (file:///F:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:9:401635)

**Comment by JarvisHsu** [comment]
Q: ns.corporation.hasUnlockUpgrade is not a function 
A: Refer to this [bitburner.corporation.md](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.corporation.md)
